"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class gps_t(object):

    __slots__ = ["epoch", "timestamp", "is_ucm_valid", "ucm_x", "ucm_y", "is_gga_alive", "gga_lat", "gga_lon", "gga_fixq", "gga_nsat", "gga_hdop", "gga_alt", "gga_geoid", "is_rmc_alive", "sog_mps", "cog_deg"]

    __typenames__ = ["int64_t", "int64_t", "boolean", "double", "double", "boolean", "double", "double", "int8_t", "int8_t", "double", "double", "double", "boolean", "double", "double"]

    __dimensions__ = [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]

    def __init__(self):
        self.epoch = 0
        """ LCM Type: int64_t """
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.is_ucm_valid = False
        """ LCM Type: boolean """
        self.ucm_x = 0.0
        """ LCM Type: double """
        self.ucm_y = 0.0
        """ LCM Type: double """
        self.is_gga_alive = False
        """ LCM Type: boolean """
        self.gga_lat = 0.0
        """ LCM Type: double """
        self.gga_lon = 0.0
        """ LCM Type: double """
        self.gga_fixq = 0
        """ LCM Type: int8_t """
        self.gga_nsat = 0
        """ LCM Type: int8_t """
        self.gga_hdop = 0.0
        """ LCM Type: double """
        self.gga_alt = 0.0
        """ LCM Type: double """
        self.gga_geoid = 0.0
        """ LCM Type: double """
        self.is_rmc_alive = False
        """ LCM Type: boolean """
        self.sog_mps = 0.0
        """ LCM Type: double """
        self.cog_deg = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(gps_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qqbddbddbbdddbdd", self.epoch, self.timestamp, self.is_ucm_valid, self.ucm_x, self.ucm_y, self.is_gga_alive, self.gga_lat, self.gga_lon, self.gga_fixq, self.gga_nsat, self.gga_hdop, self.gga_alt, self.gga_geoid, self.is_rmc_alive, self.sog_mps, self.cog_deg))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != gps_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return gps_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = gps_t()
        self.epoch, self.timestamp = struct.unpack(">qq", buf.read(16))
        self.is_ucm_valid = bool(struct.unpack('b', buf.read(1))[0])
        self.ucm_x, self.ucm_y = struct.unpack(">dd", buf.read(16))
        self.is_gga_alive = bool(struct.unpack('b', buf.read(1))[0])
        self.gga_lat, self.gga_lon, self.gga_fixq, self.gga_nsat, self.gga_hdop, self.gga_alt, self.gga_geoid = struct.unpack(">ddbbddd", buf.read(42))
        self.is_rmc_alive = bool(struct.unpack('b', buf.read(1))[0])
        self.sog_mps, self.cog_deg = struct.unpack(">dd", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if gps_t in parents: return 0
        tmphash = (0xed806427a7eda8a2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if gps_t._packed_fingerprint is None:
            gps_t._packed_fingerprint = struct.pack(">Q", gps_t._get_hash_recursive([]))
        return gps_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", gps_t._get_packed_fingerprint())[0]

